struct dataObjInfo (obj, name, stack)
struct dataStackInfo (position, name, propsInfo)
struct dataPropInfo (name, class, value)



-- make object list
mySelection = objects as Array

-- create stack info for each object
for obj in mySelection do
(
	stackInfo
	append myArrayLevel1 #()
)



/*-------------------------------------------------------------------------------------------------
-- Temp Code Start
---------------------------------------------------------------------------------------------------

curMod = 1
curModName = $.modifiers[position]
curModProps = getPropNames $.modifiers[position]

myModTest = myMod position:curMod name:curModName props:curModProps 






---------------------------------------------------------------------------------------------------
-- Temp Code End
-------------------------------------------------------------------------------------------------*/

