roAnim.axObj.Picture=roAnim.ilTv.ListImages[3].Picture
roAnim.axObj.PictureAlignment=#lvwTile

roAnim.axObj.ColumnHeaderIcons=roAnim.ilTv
roAnim.axObj.Icons

show roAnim.axObj

roAnim.axObj.ColumnHeaders[3].Left=0.0

roAnim.axObj.TextBackground = #lvwTransparent --| #lvwOpaque )
roAnim.axObj.SmallIcons=true
roAnim.axObj.LabelWrap=true
roAnim.axObj.listitems[1].text=" jhkjh kjhk hjhg jgj hgjhg jhgj h"