rollout inet "internet control" width:800 height:800
(
	--ActiveXControl tran1 "Microsoft Internet Transfer Control 6.0" pos:[0,0] width:10 height:10
	ActiveXControl tran1 "Internet Transfer Control" pos:[0,0] width:10 height:10
	--ActiveXControl in1 "HHCtrl Object" pos:[13,7] width:800 height:800
	editText edt1 "" pos:[8,24] width:144 height:168

on inet open do
	(
	--in1.Navigate "E:\\2_Current_Jobs\\pondskata\\index.html"
	--tran1.

	)
)
createdialog inet