	on mi_TransParPRS picked do	doTrans 1 1 1 1
	on mi_TransParPR picked do	doTrans 1 1 0 1
	on mi_TransParP picked do	doTrans 1 0 0 1
	on mi_TransParR picked do	doTrans 0 1 0 1
	on mi_TransParS picked do	doTrans 0 0 1 1

	on mi_TransPRS picked do	doTrans 1 1 1 0
	on mi_TransPR picked do		doTrans 1 1 0 0
	on mi_TransP picked do		doTrans 1 0 0 0
	on mi_TransR picked do		doTrans 0 1 0 0
	on mi_TransS picked do		doTrans 0 0 1 0
